force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/ActiveModules__c.field-meta.xml
<CustomField>
    <fullName>ActiveModules__c</fullName>
    <label>Active Modules</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/EndDatetime__c.field-meta.xml
<CustomField>
    <fullName>EndDatetime__c</fullName>
    <label>End Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/KeyDependencies__c.field-meta.xml
<CustomField>
    <fullName>KeyDependencies__c</fullName>
    <label>Key Dependencies</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <label>Start Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/SubscriptionMode__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionMode__c</fullName>
    <inlineHelpText>Choose &quot;Manual&quot; to require members to join a course before participating, or &quot;Automatic&quot; to allow members to jump right into taking modules.</inlineHelpText>
    <label>Subscription Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PackageInstallationTest.cls
@isTest
public  class PackageInstallationTest {

    @isTest
    static void testSpring21Install() {
        PackageInstallation postinstall = new PackageInstallation();

        System.Test.startTest();
            List<FieloELR__Course__c> courses = new List<FieloELR__Course__c>();
            List<FieloPLT__Program__c> programs;
            List<FieloPLT__Segment__c> segments;

            programs = MockUpFactory.createPrograms('Default', 1);
            insert programs;

            courses = MockUpFactory.createCourses(programs.get(0).id, null, 1);
            courses.get(0).ActiveModules__c = 0;
            courses.get(0).Status__c = 'Draft';
            courses.get(0).KeyDependencies__c = '';
            courses.get(0).SubscriptionMode__c = 'Manual';
            courses.get(0).StartDateTime__c = null;
            courses.get(0).EndDateTime__c = null;
            courses.get(0).StartDate__c = System.today();
            courses.get(0).EndDate__c = System.today();
            insert courses;

            courses = [SELECT Id, StartDate__c, StartDatetime__c, EndDate__c, EndDatetime__c FROM Course__c];

            System.assert(courses.get(0).StartDatetime__c == null, 'Start datetime should be null');

            Test.testInstall(postinstall, new Version(1,75,1));
        System.Test.stopTest();

        courses = [SELECT Id, StartDate__c, StartDatetime__c, EndDate__c, EndDatetime__c FROM Course__c];

        System.assertEquals((Datetime) courses.get(0).StartDate__c, courses.get(0).StartDatetime__c, 'Wrong start datetime' );
        System.assertEquals((Datetime) courses.get(0).EndDate__c, courses.get(0).EndDatetime__c, 'Wrong start datetime' );
    }
}